from __future__ import annotations

import argparse
import sys
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from app.agent import DEFAULT_QUESTION, MovieEvidencePromptCore  # noqa: E402


DEFAULT_MANIFEST = "divergence_evidence_artifacts/chroma_divergence_evidence_manifest.json"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Print a movie evidence prompt from notebook-generated Chroma data."
    )
    parser.add_argument(
        "movie_key",
        help="Movie key to load from Chroma, for example tt0036628_1305158.",
    )
    parser.add_argument(
        "--manifest",
        default=DEFAULT_MANIFEST,
        help="Path to the Chroma evidence manifest generated by the notebook.",
    )
    parser.add_argument(
        "--question",
        default=DEFAULT_QUESTION,
        help="Question to include in the generated prompt.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    core = MovieEvidencePromptCore.from_manifest(args.manifest)
    payload = core.build_movie_prompt(args.movie_key, question=args.question)

    print(f"Movie key: {payload.movie_key}")
    print(f"Evidence documents: {len(payload.evidence)}")
    print(f"Evidence pairs: {payload.pair_count}")
    print()
    print("=" * 80)
    print(payload.system_prompt)
    print()
    print("=" * 80)
    print(payload.user_prompt)
    print()


if __name__ == "__main__":
    main()
